apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  integration_pem: "{{ .Values.github.integrationPem }}"
  integration_id: "{{ .Values.github.integrationId }}"
  gitlab_user: "{{ .Values.gitlab.user }}"
  gitlab_token: "{{ .Values.gitlab.token }}"
